revoke.py：防撤回
（实验性）防撤回且保留提示。方案来自 EEEEhex/RevokeHook 项目。
撤回提示会显示在对应的消息下方。
远程撤回时，撤回提示需要重新进入聊天窗口才会刷新出来。
电脑端自己撤回时，消息会变成撤回提示，消息本身需要重进聊天窗口才会再次刷新出来。
不拦截自己撤回、拍一拍防撤回正在研究。

coexist.py：共存
创建一个编号 0~9 的共存版 Weixinζ.exe（最多十个），隔离其互斥锁、窗口名、设置、登录端口。
共存版的所有消息记录和原版共用，可以随意换着登录。

sound_extract.py：提取提示音
提取提示音到当前目录，文件名为 Sound_编号_十六进制大小.wav。

sound_replace.py：修改提示音
替换提示音，新的音频必须为 WAV 格式，采样率 44100，大小不能超过原版（超过会截断）。

Sound 0 000110D0：锁定
Sound 1 0001678C：新消息通知
Sound 2 00022E2C：通话接通/挂断
Sound 3 000857AE：通话来电铃声
Sound 4 000126E0：解锁
legacy/unmutex.py：旧的多开
移除 4.0.3+ 互斥锁检测，允许多次启动同一个微信程序。该修改已弃用。
不要用于登录多个账号，配置冲突会导致闪退，请用共存。

legacy/revoke.py：旧的防撤回无提示
抑制 revokemsg 撤回指令消息，消息无法被撤回，没有撤回提示。
